# Generated by Django 4.0.5 on 2022-06-09 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_alter_list_options_alter_task_options_board_uuid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, verbose_name='Beschreibung'),
        ),
        migrations.AlterField(
            model_name='list',
            name='order',
            field=models.SmallIntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name='task',
            name='order',
            field=models.SmallIntegerField(default=1000),
        ),
    ]
