# Generated by Django 4.0.5 on 2022-06-15 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0004_task_description_alter_list_order_alter_task_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='order',
            field=models.SmallIntegerField(db_index=True, default=1000),
        ),
        migrations.AlterField(
            model_name='task',
            name='order',
            field=models.SmallIntegerField(db_index=True, default=1000),
        ),
    ]
